// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace placeholder values with your project config.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// **Setup:** After creating a Firebase project, run:
/// ```bash
/// dart pub global activate flutterfire_cli
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholders by running `flutterfire configure`.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNOwTnJYQiADnvgPxuQcVAblGESZdAZiA',
    appId: '1:852379129535:android:e5be5067f1074ae7c2180a',
    messagingSenderId: '852379129535',
    projectId: 'alu-talent-connect-app-be129',
    storageBucket: 'alu-talent-connect-app-be129.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fbPst6FYo2Hz5bwjyB6Q4rWPj2vOd5I',
    appId: '1:852379129535:web:040d76bdf9db6bcfc2180a',
    messagingSenderId: '852379129535',
    projectId: 'alu-talent-connect-app-be129',
    authDomain: 'alu-talent-connect-app-be129.firebaseapp.com',
    storageBucket: 'alu-talent-connect-app-be129.firebasestorage.app',
    measurementId: 'G-M4F1ZKJQGR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbBKz0lNqFYZPWFpMXTQ9QBl1JaLsgtw',
    appId: '1:852379129535:ios:96319f470353f65ec2180a',
    messagingSenderId: '852379129535',
    projectId: 'alu-talent-connect-app-be129',
    storageBucket: 'alu-talent-connect-app-be129.firebasestorage.app',
    iosBundleId: 'com.alu.aluTalentConnect',
  );
}
